blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs),
    path('<int:id>/', views.details, name = 'newblog')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from projects import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name = 'home'),
    path('blogs/', include('blog.urls'), name = 'newblog')

]

urlpatterns+=(static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT))

blog/models.py
from django.db import models

class Blog(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField(blank = "False")
    desc = models.CharField(max_length = 250)

    def __str__(self):
        return self.name 

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length = 100)
    desc = models.CharField(max_length=200)
    image = models.ImageField(upload_to = 'projects/media')
    url = models.URLField(blank = True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(response):
    instance = Blog.objects.all()
    return render(response, "one.html", {'returned' : instance})

def details(response, id):
    id = get_object_or_404(Blog, pk = id)
    return render(response, "details.html", {"blog_id":id})

projects/views.py
from django.shortcuts import render
from .models import Project

def homepage(response):
    instance = Project.objects.all()
    return render( response, 'projects/one.html', {'projects' : instance})

blog/templates/details.html
{% extends 'projects/basetemplate.html' %}
{% block content %}
<h1>{{blog_id.name}}</h1>
<h2>--{{blog_id.date | date:'F jS Y' | upper}}--</h2>
<p>{{blog_id.desc}}</p>

{%endblock%}

blog/templates/one.html
{% extends 'projects/basetemplate.html'%}

{%block content%}

<h2>There are {{returned.count}} blog{{returned.count | pluralize}}</h2>

{%for i in returned%}

<a href = "{% url 'blog:newblog' i.id%}"><h1>{{i.name}}</h1></a>
<br>
<h5>{{i.date | date:'M d Y' | upper }}</h5>
<br>
<p>{{i.desc | truncatechars:100}}</p>


{%endfor%}

{%endblock%}

projects/templates/projects/basetemplate.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static 'projects/logo.png' %}">

  <title>Harsh's Blog</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'projects/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Harsh's Logo">
        <span>Harsh Pratik</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static 'projects/Harsh Resume_2.pdf' %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/harshpratik/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/tedmark_" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="\blogs" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  
  <br>
  <br>
  <hr>
  <ul class="nav nav-pills justify-content-center" >
    <footer>Designed by Harsh Pratik</footer>
<br>
<br>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

projects/templates/projects/one.html
{% extends 'projects/basetemplate.html' %}
{% load static %}

{% block content %}
<div class = 'container text-center'>
<img src ="{% static 'projects/DSC_0832.jpg' %}" width = "500"   height="500">
<br>
</div>


<h2 class="mt-5 text-center">Portfolio</h2>
<hr>
<div class="row">
    {%for i in projects%}
    <div class="col-lg-4 col-md-6">
        {% if i.url%}
        <a href = {{i.url}}>
        {%endif%}   
        <img src = "{{i.image.url}} " class="img-fluid mb-2"></a>
        <h2 class= "text-center">{{i.title}}</h2>
        <p class= "text-center">{{i.desc}}</p>
    </div>
    {% endfor %}
</div>  

{%endblock%}